FROM ubuntu:14.04

# Install Java.
RUN apt-get update && apt-get install -y openjdk-7-jdk && rm -rf /var/lib/apt/lists/*


# Define commonly used JAVA_HOME variable
ENV JAVA_HOME /usr/lib/jvm/java-7-openjdk-amd64

WORKDIR /data
ADD Main.java /data/
RUN javac /data/Main.java
CMD ["bash"]